-- CREATION FOREIGN KEYS --
ALTER TABLE Service
ADD CONSTRAINT FK_numDep
FOREIGN KEY (numDep) REFERENCES Departement(numDep)
ON UPDATE CASCADE,
ADD CONSTRAINT FK_idDirection
FOREIGN KEY (idDirection) REFERENCES Direction(idDirection)
ON UPDATE CASCADE,
ADD CONSTRAINT FK_idAdm
FOREIGN KEY (idAdm) REFERENCES Administration(idAdm)
ON UPDATE CASCADE;

ALTER TABLE Pointage
ADD CONSTRAINT FK_idService
FOREIGN KEY (idService) REFERENCES Service(idService)
ON UPDATE CASCADE,
ADD CONSTRAINT FK_codeIndex
FOREIGN KEY (codeIndex) REFERENCES Infraction(codeIndex)
ON UPDATE CASCADE;

ALTER TABLE Infraction
ADD CONSTRAINT FK_idIndic
FOREIGN KEY (idIndic) REFERENCES Indicateur(idIndic)
ON UPDATE CASCADE,
ADD CONSTRAINT FK_idUc
FOREIGN KEY (idUc) REFERENCES uniteCompte(idUc)
ON UPDATE CASCADE;

ALTER TABLE Direction
ADD CONSTRAINT FK_idAdmDir
FOREIGN KEY (idAdm) REFERENCES Administration(idAdm)
ON UPDATE CASCADE;

ALTER TABLE Demographie
ADD CONSTRAINT FK_numDepDemo
FOREIGN KEY (numDep) REFERENCES Departement(numDep)
ON UPDATE CASCADE;
